version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: localpw
      POSTGRES_DB: discord_community_autoroles
  app:
    build: .
    restart: always
    ports:
      - "9000:8080"
    links:
      - "db"
    env_file: .env
